from pathlib import Path

path = Path("tests/infrastructure/test_universal_cross_asset_conformance_final_owner_r62g_guards.py")
text = path.read_text(encoding="utf-8")

old_helper = '''def _r62g_is_builtins_module(value: _Value) -> bool:\n    return _r12._contains_kind(\n        value,\n        _R62G_BUILTINS_MODULE_KIND,\n    ) and not _r12._contains_kind(value, "container-kind", "mapping")\n\n\n'''
new_helper = '''def _r62g_is_builtins_module(value: _Value) -> bool:\n    return _r12._contains_kind(\n        value,\n        _R62G_BUILTINS_MODULE_KIND,\n    ) and not _r12._contains_kind(value, "container-kind")\n\n\ndef _r62g_is_side_effect_free_expression(node: ast.AST) -> bool:\n    if isinstance(node, (ast.Name, ast.Constant)):\n        return True\n    if isinstance(node, (ast.Attribute, ast.Starred)):\n        return _r62g_is_side_effect_free_expression(node.value)\n    if isinstance(node, ast.Subscript):\n        return _r62g_is_side_effect_free_expression(\n            node.value\n        ) and _r62g_is_side_effect_free_expression(node.slice)\n    if isinstance(node, (ast.Tuple, ast.List, ast.Set)):\n        return all(_r62g_is_side_effect_free_expression(item) for item in node.elts)\n    if isinstance(node, ast.Dict):\n        return all(\n            (key is None or _r62g_is_side_effect_free_expression(key))\n            and _r62g_is_side_effect_free_expression(value)\n            for key, value in zip(node.keys, node.values, strict=True)\n        )\n    if isinstance(node, ast.IfExp):\n        return all(\n            _r62g_is_side_effect_free_expression(item)\n            for item in (node.test, node.body, node.orelse)\n        )\n    if isinstance(node, ast.BoolOp):\n        return all(_r62g_is_side_effect_free_expression(item) for item in node.values)\n    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):\n        return _r62g_is_side_effect_free_expression(\n            node.left\n        ) and _r62g_is_side_effect_free_expression(node.right)\n    return False\n\n\n'''
assert text.count(old_helper) == 1, "builtins module helper anchor mismatch"
text = text.replace(old_helper, new_helper)

old_subscript = '''    def _evaluate_subscript(\n        self,\n        node: ast.Subscript,\n        environment: dict[str, _Value],\n    ) -> _Value:\n        if isinstance(node.value, ast.Name):\n            receiver = self._scan_expression(node.value, environment)\n            if _r62g_is_builtins_module(receiver):\n                self._scan_expression(node.slice, environment)\n                return _UNKNOWN\n        return super()._evaluate_subscript(node, environment)\n'''
new_subscript = '''    def _evaluate_subscript(\n        self,\n        node: ast.Subscript,\n        environment: dict[str, _Value],\n    ) -> _Value:\n        if _r62g_is_side_effect_free_expression(node.value):\n            receiver = self._scan_expression(node.value, environment)\n            if _r62g_is_builtins_module(receiver):\n                self._scan_expression(node.slice, environment)\n                return _UNKNOWN\n        return super()._evaluate_subscript(node, environment)\n'''
assert text.count(old_subscript) == 1, "subscript anchor mismatch"
text = text.replace(old_subscript, new_subscript)

old_call = '''    def _evaluate_call(\n        self,\n        node: ast.Call,\n        environment: dict[str, _Value],\n    ) -> _Value:\n        if (\n            isinstance(node.func, ast.Attribute)\n            and node.func.attr in {"get", "__getitem__"}\n            and isinstance(node.func.value, ast.Name)\n        ):\n            receiver = self._scan_expression(node.func.value, environment)\n            if _r62g_is_builtins_module(receiver):\n                for argument in node.args:\n                    self._scan_expression(argument, environment)\n                for keyword in node.keywords:\n                    self._scan_expression(keyword.value, environment)\n                return _UNKNOWN\n        return super()._evaluate_call(node, environment)\n'''
new_call = '''    def _evaluate_call(\n        self,\n        node: ast.Call,\n        environment: dict[str, _Value],\n    ) -> _Value:\n        if (\n            isinstance(node.func, ast.Attribute)\n            and node.func.attr in {"get", "__getitem__"}\n            and _r62g_is_side_effect_free_expression(node.func.value)\n        ):\n            receiver = self._scan_expression(node.func.value, environment)\n            if _r62g_is_builtins_module(receiver):\n                for argument in node.args:\n                    self._scan_expression(argument, environment)\n                for keyword in node.keywords:\n                    self._scan_expression(keyword.value, environment)\n                return _UNKNOWN\n        return super()._evaluate_call(node, environment)\n'''
assert text.count(old_call) == 1, "call anchor mismatch"
text = text.replace(old_call, new_call)

anchor = '''def test_r62g_real_builtins_mappings_remain_fail_closed() -> None:\n'''
regression = '''def test_r62g_transported_builtins_module_mapping_misuse_stays_safe() -> None:\n    sources = (\n        'import builtins\\nresult = (builtins,)[0]["eval"]("1+1")\\n',\n        'import builtins\\nresult = [builtins][0]["eval"]("1+1")\\n',\n        (\n            'import builtins\\nholder = (builtins,)\\n'\n            'result = holder[0].get("eval")("1+1")\\n'\n        ),\n        (\n            'import builtins\\nholder = (builtins,)\\n'\n            'result = holder[0].__getitem__("eval")("1+1")\\n'\n        ),\n    )\n\n    for source in sources:\n        assert _r62g_runtime_mapping_error(source) in {TypeError, AttributeError}\n        assert not any(\n            marker.startswith("call:")\n            for marker in _r62g_dynamic_execution_markers_from_source(source)\n        )\n\n\n'''
assert text.count(anchor) == 1, "regression insertion anchor mismatch"
text = text.replace(anchor, regression + anchor)

path.write_text(text, encoding="utf-8")
