from datetime import datetime
from pathlib import Path

from qore.infrastructure.traders.vt08_b01_r3_8 import Vt08B01Bar as Vt08B01Bar
from qore.kernel.errors import InfrastructureError

class Vt08B01BacktestError(InfrastructureError): ...

class Vt08B01BacktestTrade: ...

class Vt08B01BacktestReport:
    def payload(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...

def _load(path: Path) -> tuple[str, str, datetime, str, tuple[Vt08B01Bar, ...]]: ...

def run_vt08_b01_backtest(path: Path) -> Vt08B01BacktestReport: ...
