"""R2-BZ USDJPY cognitive experience sovereignty walk-forward.

USDJPY receives its own Experience Memory.  No AUDUSD state is transferred.

Frozen state:
- REF_DELAY_OVERLAP from R2-BU;
- prior 4Y -> next 1Y OOS;
- expected R + dead-on-arrival rate;
- empirical-Bayes shrinkage with the already-used support/prior constants.

Cognitive mapping:
- positive expected R + lower-than-baseline DOA -> KNOWN -> may EXECUTE;
- non-positive expected R + non-improved DOA -> CONFLICTED -> ABSTAIN;
- mixed evidence -> PARTIAL -> WAIT;
- insufficient support -> UNKNOWN -> WAIT.

The final action is generated by crt_pure_cognitive_state.reason().
No future outcome is exposed to the Situation Model.

Research only.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from qore.infrastructure.trader_lab.vt08_crt_pure_r2_model1_reference_lab import (
    Model1LabTrade,
    _summary,
)
from qore.infrastructure.trader_lab.vt08_crt_pure_r2bc_usdjpy_confirmation_geometry_atlas import (
    END,
    START,
    run_atlas,
)
from qore.infrastructure.trader_lab.vt08_crt_pure_r2bl_usdjpy_pf_root_cause import (
    PathRecord,
    run_forensics,
)
from qore.infrastructure.trader_lab.vt08_crt_pure_r2bn_usdjpy_root_cause_expected_r_wf import (
    MIN_CELL_SUPPORT,
    PRIOR_STRENGTH,
)
from qore.infrastructure.trader_lab.vt08_crt_pure_r2bu_usdjpy_overlap_expected_r_wf import (
    _record as _overlap_record,
)
from qore.infrastructure.trader_lab.vt08_crt_pure_r2m_survivor_robustness import (
    _stress_summary,
)
from qore.infrastructure.traders.crt_pure_cognitive_contract import (
    CrtPureAttentionState,
    CrtPureHypothesisStage,
    CrtPureKnowledgeState,
    CrtPureReasoningAction,
)
from qore.infrastructure.traders.crt_pure_cognitive_state import (
    CrtPureCausalObservation,
    CrtPureReasoningDecision,
    CrtPureSituationModel,
    reason,
)
from qore.infrastructure.traders.crt_pure_identity import CrtPureMarket
from qore.infrastructure.traders.crt_pure_strategy_identity_memory import (
    strategy_identity_ready,
)

IDENTITY = "VT08_CRT_PURE_R2BZ_USDJPY_COGNITIVE_EXPERIENCE_WF_001"
SCHEMA = "qore.vt08.crt_pure.r2bz_usdjpy_cognitive_experience_wf.v1"
MARKET = CrtPureMarket.USDJPY
TRAINING_YEARS = 4
MIN_DENSITY_PER_YEAR = 170.0
COST_DIAGNOSTICS_R: tuple[float, ...] = (0.02, 0.05)


@dataclass(frozen=True, slots=True)
class CognitiveRecord:
    trade: Model1LabTrade
    key: str
    dead_on_arrival: bool


@dataclass(frozen=True, slots=True)
class ExperienceCell:
    key: str
    support: int
    expected_r: float
    doa_rate: float


@dataclass(frozen=True, slots=True)
class ExperienceModel:
    baseline_mean_r: float
    baseline_doa_rate: float
    cells: tuple[ExperienceCell, ...]

    def lookup(self, key: str) -> ExperienceCell | None:
        return next((cell for cell in self.cells if cell.key == key), None)


def _trade_key(trade: Model1LabTrade) -> tuple[str, str, str, str, str]:
    return (
        trade.source_opened_at,
        trade.confirmation_opened_at,
        trade.entry_opened_at,
        trade.parent_direction,
        trade.timing_triplet,
    )


def _is_doa(record: PathRecord) -> bool:
    return (
        record.trade.exit_reason == "STOP"
        and abs(float(record.trade.r_multiple) + 1.0) <= 1e-9
        and record.max_completed_close_r_before_exit < 0.25
    )


def _build_records() -> tuple[tuple[CognitiveRecord, ...], dict[str, int]]:
    confirmation, _ = run_atlas()
    paths, _ = run_forensics()

    overlap_by_key = {
        _trade_key(row.trade): _overlap_record(row)
        for row in confirmation
    }
    path_by_key = {_trade_key(row.trade): row for row in paths}
    common = sorted(set(overlap_by_key) & set(path_by_key))
    records = tuple(
        CognitiveRecord(
            trade=path_by_key[key].trade,
            key=(
                f"{overlap_by_key[key].reference}|"
                f"{overlap_by_key[key].delay}|"
                f"{overlap_by_key[key].overlap}"
            ),
            dead_on_arrival=_is_doa(path_by_key[key]),
        )
        for key in common
    )
    diagnostics = {
        "confirmation_records": len(confirmation),
        "path_records": len(paths),
        "common_records": len(records),
        "confirmation_only": len(set(overlap_by_key) - set(path_by_key)),
        "path_only": len(set(path_by_key) - set(overlap_by_key)),
    }
    return records, diagnostics


def _year_start(year: int) -> datetime:
    return datetime(year, 9, 21, 0, 0, tzinfo=UTC)


def _slice(
    records: tuple[CognitiveRecord, ...],
    start: datetime,
    end: datetime,
) -> tuple[CognitiveRecord, ...]:
    return tuple(
        row
        for row in records
        if start <= datetime.fromisoformat(row.trade.entry_opened_at) < end
    )


def _fit(
    training: tuple[CognitiveRecord, ...],
) -> tuple[ExperienceModel, dict[str, Any]]:
    if not training:
        return (
            ExperienceModel(
                baseline_mean_r=0.0,
                baseline_doa_rate=0.0,
                cells=(),
            ),
            {"reason": "EMPTY_TRAINING"},
        )

    baseline_mean = sum(float(row.trade.r_multiple) for row in training) / len(training)
    baseline_doa = sum(row.dead_on_arrival for row in training) / len(training)
    counts: Counter[str] = Counter()
    r_sums: defaultdict[str, float] = defaultdict(float)
    doa_counts: Counter[str] = Counter()
    for row in training:
        counts[row.key] += 1
        r_sums[row.key] += float(row.trade.r_multiple)
        doa_counts[row.key] += int(row.dead_on_arrival)

    cells: list[ExperienceCell] = []
    for key, count in sorted(counts.items()):
        if count < MIN_CELL_SUPPORT:
            continue
        expected_r = (
            r_sums[key] + PRIOR_STRENGTH * baseline_mean
        ) / (count + PRIOR_STRENGTH)
        doa_rate = (
            doa_counts[key] + PRIOR_STRENGTH * baseline_doa
        ) / (count + PRIOR_STRENGTH)
        cells.append(
            ExperienceCell(
                key=key,
                support=count,
                expected_r=round(expected_r, 10),
                doa_rate=round(doa_rate, 10),
            )
        )

    return (
        ExperienceModel(
            baseline_mean_r=baseline_mean,
            baseline_doa_rate=baseline_doa,
            cells=tuple(cells),
        ),
        {
            "baseline_mean_r": round(baseline_mean, 10),
            "baseline_doa_rate": round(baseline_doa, 10),
            "eligible_cells": len(cells),
            "cells": [asdict(cell) for cell in cells],
        },
    )


def _knowledge(
    model: ExperienceModel,
    record: CognitiveRecord,
) -> tuple[CrtPureKnowledgeState, tuple[str, ...], tuple[str, ...], ExperienceCell | None]:
    cell = model.lookup(record.key)
    if cell is None:
        return (
            CrtPureKnowledgeState.UNKNOWN,
            (),
            ("EXPERIENCE_CELL_UNRESOLVED",),
            None,
        )

    positive_r = cell.expected_r > 0.0
    lower_doa = cell.doa_rate < model.baseline_doa_rate
    if positive_r and lower_doa:
        return CrtPureKnowledgeState.KNOWN, (), (), cell
    if (not positive_r) and (not lower_doa):
        return (
            CrtPureKnowledgeState.CONFLICTED,
            ("EXPERIENCE_NEGATIVE_R_AND_HIGH_DOA",),
            (),
            cell,
        )
    return (
        CrtPureKnowledgeState.PARTIAL,
        (),
        ("EXPERIENCE_MIXED_R_DOA_EVIDENCE",),
        cell,
    )


def _decision(
    model: ExperienceModel,
    record: CognitiveRecord,
) -> CrtPureReasoningDecision:
    trade = record.trade
    observed_at = datetime.fromisoformat(trade.entry_opened_at)
    knowledge, contradictions, uncertainties, cell = _knowledge(model, record)
    observations = [
        CrtPureCausalObservation(
            name="EXPERIENCE_CELL",
            observed_at=observed_at,
            value_token=record.key,
        )
    ]
    if cell is not None:
        observations.extend(
            (
                CrtPureCausalObservation(
                    name="EXPERIENCE_EXPECTED_R",
                    observed_at=observed_at,
                    value_token=f"{cell.expected_r:.8f}",
                ),
                CrtPureCausalObservation(
                    name="EXPERIENCE_DOA_RATE",
                    observed_at=observed_at,
                    value_token=f"{cell.doa_rate:.8f}",
                ),
            )
        )

    state = CrtPureSituationModel(
        market=MARKET,
        observed_at=observed_at,
        hypothesis_id=(
            f"USDJPY:{trade.source_opened_at}:{trade.confirmation_opened_at}"
        ),
        source_event_id=trade.source_opened_at,
        event_generation=1,
        attention_state=CrtPureAttentionState.DECISION,
        hypothesis_stage=CrtPureHypothesisStage.CONFIRMED,
        data_integrity_ok=True,
        strategy_identity_ready=strategy_identity_ready(),
        source_event_present=True,
        confirmation_complete=True,
        destination_context_known=True,
        destination_available=True,
        execution_data_fresh=True,
        knowledge_state=knowledge,
        contradictions=contradictions,
        uncertainties=uncertainties,
        market_context_tokens=(record.key,),
        observations=tuple(observations),
    )
    return reason(state)


def _metrics(records: tuple[CognitiveRecord, ...]) -> dict[str, Any]:
    trades = tuple(row.trade for row in records)
    summary = _summary(trades)
    dead = sum(row.dead_on_arrival for row in records)
    return {
        **summary,
        "dead_on_arrival": dead,
        "dead_on_arrival_rate": (
            0.0 if not records else round(dead / len(records), 8)
        ),
        "cost_stress": {
            f"COST_{cost:.2f}R": _stress_summary(trades, cost)
            for cost in COST_DIAGNOSTICS_R
        },
    }


def run_walk_forward() -> tuple[
    tuple[CognitiveRecord, ...],
    dict[str, Any],
]:
    records, source_diagnostics = _build_records()
    baseline_oos: list[CognitiveRecord] = []
    action_rows: dict[CrtPureReasoningAction, list[CognitiveRecord]] = {
        action: [] for action in CrtPureReasoningAction
    }
    folds: list[dict[str, Any]] = []

    for oos_year in range(START.year + TRAINING_YEARS, END.year):
        training = _slice(
            records,
            _year_start(oos_year - TRAINING_YEARS),
            _year_start(oos_year),
        )
        oos = _slice(
            records,
            _year_start(oos_year),
            _year_start(oos_year + 1),
        )
        model, fit = _fit(training)
        per_action: dict[CrtPureReasoningAction, list[CognitiveRecord]] = {
            action: [] for action in CrtPureReasoningAction
        }
        reason_counts: Counter[str] = Counter()
        for row in oos:
            decision = _decision(model, row)
            per_action[decision.action].append(row)
            action_rows[decision.action].append(row)
            reason_counts.update(decision.auditable_why)

        baseline_oos.extend(oos)
        folds.append(
            {
                "training_start": _year_start(
                    oos_year - TRAINING_YEARS
                ).isoformat(),
                "oos_start": _year_start(oos_year).isoformat(),
                "fit": fit,
                "oos_baseline": _metrics(oos),
                "actions": {
                    action.value: {
                        "count": len(per_action[action]),
                        "metrics": _metrics(tuple(per_action[action])),
                    }
                    for action in CrtPureReasoningAction
                },
                "auditable_why_counts": dict(reason_counts),
            }
        )

    baseline = tuple(
        sorted(baseline_oos, key=lambda row: row.trade.entry_opened_at)
    )
    frozen_actions = {
        action: tuple(
            sorted(
                action_rows[action],
                key=lambda row: row.trade.entry_opened_at,
            )
        )
        for action in CrtPureReasoningAction
    }
    execute = frozen_actions[CrtPureReasoningAction.EXECUTE]
    baseline_metrics = _metrics(baseline)
    execute_metrics = _metrics(execute)
    years = len(folds)
    execute_per_year = 0.0 if years == 0 else len(execute) / years
    positive_fraction = (
        0.0
        if not folds
        else sum(
            float(fold["actions"]["EXECUTE"]["metrics"]["total_r"]) > 0
            for fold in folds
        )
        / len(folds)
    )

    report: dict[str, Any] = {
        "schema": SCHEMA,
        "identity": IDENTITY,
        "market": MARKET.value,
        "window_start": START.isoformat(),
        "window_end_exclusive": END.isoformat(),
        "training_years": TRAINING_YEARS,
        "experience_memory": {
            "state": "REF_DELAY_OVERLAP",
            "minimum_cell_support": MIN_CELL_SUPPORT,
            "prior_strength": PRIOR_STRENGTH,
            "labels": ["EXPECTED_R", "DEAD_ON_ARRIVAL_RATE"],
            "future_outcome_visibility": False,
            "market_specific": True,
            "audusd_state_transfer": False,
            "may_rewrite_strategy_identity": False,
        },
        "cognitive_engine": (
            "qore.infrastructure.traders.crt_pure_cognitive_state.reason"
        ),
        "strategy_identity_ready": strategy_identity_ready(),
        "source_diagnostics": source_diagnostics,
        "combined_oos_baseline": baseline_metrics,
        "combined_oos_actions": {
            action.value: {
                "count": len(frozen_actions[action]),
                "metrics": _metrics(frozen_actions[action]),
            }
            for action in CrtPureReasoningAction
        },
        "execute_trades_per_year": round(execute_per_year, 8),
        "execute_positive_oos_year_fraction": round(
            positive_fraction,
            8,
        ),
        "research_checks": {
            "execute_density_ge_170": execute_per_year >= MIN_DENSITY_PER_YEAR,
            "execute_pf_improved": (
                float(execute_metrics["profit_factor"] or 0.0)
                > float(baseline_metrics["profit_factor"] or 0.0)
            ),
            "execute_total_r_improved": (
                float(execute_metrics["total_r"])
                > float(baseline_metrics["total_r"])
            ),
            "execute_doa_rate_improved": (
                float(execute_metrics["dead_on_arrival_rate"])
                < float(baseline_metrics["dead_on_arrival_rate"])
            ),
        },
        "folds": folds,
        "automatic_promotion": False,
        "research_only": True,
        "candidate_certified": False,
        "demo_eligible": False,
        "live_authorized": False,
        "real_capital_authorized": False,
        "production_authorized": False,
    }
    return records, report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    records, report = run_walk_forward()
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "report.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n"
    )
    with (args.output / "records.jsonl").open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(
                json.dumps(asdict(record), sort_keys=True, default=str) + "\n"
            )
    print(
        "CRT_R2BZ_USDJPY_COGNITIVE_EXPERIENCE_JSON="
        + json.dumps(report, sort_keys=True)
    )


if __name__ == "__main__":
    main()
