"""QORE CORE STACK V2 shared, authority-free cognitive context layer."""

from qore.infrastructure.core_stack_v2.ab import (
    DecisionABSummary,
    DecisionObservation,
    summarize_decision_ab,
)
from qore.infrastructure.core_stack_v2.adapters import (
    CoreAdapter,
    TraderCognitiveContext,
    build_shared_context,
)
from qore.infrastructure.core_stack_v2.analog_memory import (
    AnalogQuery,
    CausalAnalogMemory,
    ClosedEpisode,
)
from qore.infrastructure.core_stack_v2.architecture_freeze import (
    SUPERINTELLIGENCE_FREEZE_VERSION,
    superintelligence_freeze_contract,
    superintelligence_freeze_fingerprint,
)
from qore.infrastructure.core_stack_v2.audit import CoreAuditRecord, make_audit_record
from qore.infrastructure.core_stack_v2.compatibility import (
    CompatibilityEntry,
    CompatibilityStatus,
    compatibility_manifest,
    compatibility_manifest_fingerprint,
)
from qore.infrastructure.core_stack_v2.competing_future_intelligence import (
    CausalHorizonSnapshot,
    CompetingFutureAssessment,
    CompetingFutureState,
    HorizonFutureState,
    HorizonFutureVote,
    assess_competing_futures,
)
from qore.infrastructure.core_stack_v2.contracts import (
    CORE_STACK_VERSION,
    CognitiveState,
    CoreHypothesis,
    CoreSnapshot,
    HypothesisStatus,
    KnowledgeState,
    MarketEvent,
    PerceptionIntegrity,
    PortfolioIntent,
    PortfolioSituation,
    PositionContext,
    UncertaintyState,
    WorldState,
    freeze_facts,
)
from qore.infrastructure.core_stack_v2.drawdown_phenotype_memory import (
    DrawdownPhenotype,
    DrawdownPhenotypeAssessment,
    DrawdownPhenotypeComposition,
    DrawdownPhenotypeQuery,
    DrawdownPhenotypeRecognition,
    UniversalDrawdownPhenotypeMemory,
)
from qore.infrastructure.core_stack_v2.engine import CoreStackConfig, build_snapshot
from qore.infrastructure.core_stack_v2.environment_intelligence import (
    MarketEnvironmentAssessment,
    MarketEnvironmentObservation,
    MarketEnvironmentPolicy,
    MarketEnvironmentState,
    assess_market_environment,
)
from qore.infrastructure.core_stack_v2.instinct_intelligence import (
    InstinctAssessment,
    InstinctPolicy,
    InstinctSituation,
    SupportMethodology,
    assess_instinct,
)
from qore.infrastructure.core_stack_v2.intelligence import (
    AnalogSummary,
    CausalEdge,
    CrossMarketRelation,
    FailurePatternEvidence,
    HistoricalAnalogEvidence,
    HypothesisView,
    OpportunityDisposition,
    RegimeVector,
    SituationGraph,
    TraderOpportunityContext,
)
from qore.infrastructure.core_stack_v2.journey_intelligence import (
    JourneyAssessment,
    JourneyDisposition,
    PositionJourneyEvidence,
    assess_position_journey,
)
from qore.infrastructure.core_stack_v2.market_universe import (
    GLOBAL_MARKET_UNIVERSE_REQUIRED,
    CoreGlobalMarketUniverse,
    CoreInstrumentFamilyKnowledge,
    CoreMarketKnowledge,
    build_global_market_universe,
)
from qore.infrastructure.core_stack_v2.operational_falsification import (
    ActualTrade,
    CurveMetrics,
    OperationalFalsificationResult,
    ShadowAction,
    SharedShadowDecision,
    evaluate_real_operation_falsification,
)
from qore.infrastructure.core_stack_v2.path_intelligence import (
    PositionPathAssessment,
    PositionPathObservation,
    PositionPathPolicy,
    PositionPathState,
    assess_position_path,
)
from qore.infrastructure.core_stack_v2.realtime_trade_management import (
    RealtimeManagementPolicy,
    RealtimeTradeAction,
    RealtimeTradeManagementDirective,
    StopManagementMode,
    TargetManagementMode,
    assess_realtime_trade_management,
)
from qore.infrastructure.core_stack_v2.resident_convergence_intelligence import (
    ResidentConvergenceAssessment,
    ResidentConvergencePolicy,
    ResidentConvergenceState,
    assess_resident_convergence,
)
from qore.infrastructure.core_stack_v2.runtime import (
    CoreRuntimeCheckpoint,
    CoreRuntimeResult,
    CoreStackV2Runtime,
    SnapshotConsumer,
    SnapshotDelivery,
)
from qore.infrastructure.core_stack_v2.stop_target_discrimination import (
    StopTargetDiscrimination,
    StopTargetHypothesis,
    assess_stop_target_path,
)
from qore.infrastructure.core_stack_v2.stability_intelligence import (
    DrawdownStabilityAssessment,
    MarketStabilityEvidence,
    StabilityMode,
    StabilityPolicy,
    TraderStabilityTelemetry,
    assess_drawdown_stability,
)
from qore.infrastructure.core_stack_v2.transition_intelligence import (
    DynamicTransitionPolicy,
    MarketTrajectoryAssessment,
    MarketTrajectoryState,
    MarketTransitionObservation,
    assess_market_trajectory,
)

__all__ = [
    "CORE_STACK_VERSION",
    "CausalHorizonSnapshot",
    "CompetingFutureAssessment",
    "CompetingFutureState",
    "DrawdownPhenotype",
    "DrawdownPhenotypeAssessment",
    "DrawdownPhenotypeComposition",
    "DrawdownPhenotypeQuery",
    "DrawdownPhenotypeRecognition",
    "DrawdownStabilityAssessment",
    "JourneyAssessment",
    "InstinctAssessment",
    "InstinctPolicy",
    "InstinctSituation",
    "JourneyDisposition",
    "MarketStabilityEvidence",
    "MarketEnvironmentAssessment",
    "MarketEnvironmentObservation",
    "MarketEnvironmentPolicy",
    "MarketEnvironmentState",
    "MarketTrajectoryAssessment",
    "MarketTrajectoryState",
    "MarketTransitionObservation",
    "DynamicTransitionPolicy",
    "PositionJourneyEvidence",
    "PositionPathAssessment",
    "PositionPathObservation",
    "PositionPathPolicy",
    "PositionPathState",
    "RealtimeManagementPolicy",
    "RealtimeTradeAction",
    "RealtimeTradeManagementDirective",
    "ResidentConvergenceAssessment",
    "ResidentConvergencePolicy",
    "ResidentConvergenceState",
    "StabilityMode",
    "StopTargetDiscrimination",
    "StopTargetHypothesis",
    "StopManagementMode",
    "TargetManagementMode",
    "SupportMethodology",
    "StabilityPolicy",
    "TraderStabilityTelemetry",
    "UniversalDrawdownPhenotypeMemory",
    "TraderOpportunityContext",
    "SituationGraph",
    "RegimeVector",
    "OpportunityDisposition",
    "HypothesisView",
    "HistoricalAnalogEvidence",
    "FailurePatternEvidence",
    "CrossMarketRelation",
    "ClosedEpisode",
    "CausalEdge",
    "CausalAnalogMemory",
    "AnalogSummary",
    "AnalogQuery",
    "ActualTrade",
    "GLOBAL_MARKET_UNIVERSE_REQUIRED",
    "SUPERINTELLIGENCE_FREEZE_VERSION",
    "CognitiveState",
    "CompatibilityEntry",
    "CompatibilityStatus",
    "CoreAdapter",
    "CoreAuditRecord",
    "CurveMetrics",
    "CoreGlobalMarketUniverse",
    "CoreHypothesis",
    "CoreInstrumentFamilyKnowledge",
    "CoreMarketKnowledge",
    "CoreSnapshot",
    "CoreStackConfig",
    "CoreRuntimeCheckpoint",
    "CoreRuntimeResult",
    "CoreStackV2Runtime",
    "DecisionABSummary",
    "OperationalFalsificationResult",
    "DecisionObservation",
    "HypothesisStatus",
    "HorizonFutureState",
    "HorizonFutureVote",
    "KnowledgeState",
    "MarketEvent",
    "PerceptionIntegrity",
    "PortfolioIntent",
    "PortfolioSituation",
    "PositionContext",
    "ShadowAction",
    "SharedShadowDecision",
    "SnapshotConsumer",
    "SnapshotDelivery",
    "TraderCognitiveContext",
    "UncertaintyState",
    "WorldState",
    "assess_drawdown_stability",
    "assess_stop_target_path",
    "assess_competing_futures",
    "assess_instinct",
    "assess_market_environment",
    "assess_market_trajectory",
    "assess_position_journey",
    "assess_position_path",
    "assess_realtime_trade_management",
    "assess_resident_convergence",
    "build_global_market_universe",
    "build_shared_context",
    "build_snapshot",
    "compatibility_manifest",
    "compatibility_manifest_fingerprint",
    "evaluate_real_operation_falsification",
    "freeze_facts",
    "make_audit_record",
    "summarize_decision_ab",
    "superintelligence_freeze_contract",
    "superintelligence_freeze_fingerprint",
]
