"""Frozen architecture contract for QORE CORE STACK V2 SUPERINTELLIGENCE."""
from __future__ import annotations

import hashlib
import json
from typing import Final

SUPERINTELLIGENCE_FREEZE_VERSION: Final = "QORE_CORE_STACK_V2_SUPERINTELLIGENCE_006"

_CAPABILITIES: Final = (
    "PERCEPTION_INTEGRITY",
    "HISTORICAL_CAUSAL_MARKET_MEMORY",
    "DEEP_MARKET_WORLD_MODEL",
    "REGIME_AND_TRANSITION_INTELLIGENCE",
    "ATTENTION_AND_CHANGE_DETECTION",
    "HYPOTHESIS_ENSEMBLE",
    "UNCERTAINTY_AND_METACOGNITION",
    "GLOBAL_CROSS_MARKET_INTELLIGENCE",
    "OPPORTUNITY_SUITABILITY_BY_TRADER",
    "FAILURE_AND_COUNTERFACTUAL_MEMORY",
    "POSITION_JOURNEY_AND_ECONOMIC_ATTRIBUTION",
    "UNIVERSAL_DRAWDOWN_STABILITY_INTELLIGENCE",
    "DYNAMIC_MARKET_DETERIORATION_RECOVERY_INTELLIGENCE",
    "ADVERSE_MARKET_ENVIRONMENT_INTELLIGENCE",
    "LOSS_CLUSTER_PREVENTION_INTELLIGENCE",
    "RECOVERY_AND_EDGE_RESTORATION_INTELLIGENCE",
    "OPPORTUNITY_QUALITY_INTELLIGENCE",
    "WINNER_PROTECTION_INTELLIGENCE",
    "CAUSAL_POSITION_PATH_ASYMMETRY_INTELLIGENCE",
    "MARKET_EXPANSION_CAPACITY_INTELLIGENCE",
    "ANOMALY_FUSION_INTELLIGENCE",
    "MARKET_CONTEXT_MEMORY",
    "ULTRAFAST_INSTINCT_HOT_PATH_INTELLIGENCE",
    "UNIVERSAL_POSITION_JOURNEY_INTELLIGENCE",
    "TRADER_ADAPTER_TRANSLATION_LAYER",
)

_MARKET_UNIVERSE_SOURCES: Final = (
    "ExecutiveMarketsReadModel",
    "InstrumentUniverseRegistrySnapshot",
)

_AUTHORITY_CHAIN: Final = (
    "MARKET_AND_CIBO",
    "SHARED_CORE_V2",
    "COGNITIVE_ADAPTER",
    "TRADER_COGNITION",
    "TRADER_METHODOLOGY",
    "QORE_RISK",
    "EXECUTION",
)


def superintelligence_freeze_contract() -> dict[str, object]:
    """Return the Owner-approved immutable architecture direction."""
    return {
        "schema": "qore.core_stack_v2.superintelligence_freeze.v1",
        "freeze_version": SUPERINTELLIGENCE_FREEZE_VERSION,
        "objective": (
            "shared causal market intelligence that materially improves specialist "
            "trader quality without owning specialist methodology"
        ),
        "authority_chain": _AUTHORITY_CHAIN,
        "capabilities": _CAPABILITIES,
        "transversal_scope": {
            "shared_core_is_qore_wide": True,
            "shared_core_is_not_a_vt31_module": True,
            "vt31_role": "PRIMARY_FALSIFICATION_LAB_ONLY",
            "all_enabled_traders_may_consume_shared_context": True,
            "shared_understands_market_once_then_adapters_translate": True,
            "same_market_context_may_yield_different_trader_decisions": True,
            "adapter_required_for_methodology_specific_translation": True,
            "shared_is_third_eye_cognitive_support_for_every_enabled_trader": True,
            "shared_must_observe_what_specialist_methodology_does_not_explicitly_model": True,
            "shared_must_support_full_market_lifecycle_not_only_entry_filtering": True,
            "explicitly_excluded_traders_remain_excluded_until_owner_changes_governance": True,
        },
        "generic_ontology_law": {
            "core_concepts": (
                "trend",
                "range",
                "compression",
                "expansion",
                "volatility",
                "anomaly",
                "liquidity",
                "structure",
                "displacement",
                "momentum",
                "exhaustion",
                "reversal",
                "continuation",
                "regime_transition",
                "correlation",
                "divergence",
                "market_leadership",
                "synchronization",
                "behavior_change",
                "uncertainty",
                "path_capacity",
                "position_deterioration",
                "adverse_environment_formation",
                "environment_persistence",
                "edge_environment_restoration",
                "opportunity_quality",
                "winner_protection",
                "expansion_capacity",
                "anomaly_fusion",
            ),
            "trader_specific_ontology_forbidden_in_shared_core": True,
            "vt31_specific_concepts_belong_in_adapter_or_lab": True,
            "examples_forbidden_as_shared_core_primitives": (
                "silver_bullet",
                "vt31_raid",
                "vt31_breaker",
                "vt31_fvg",
                "vt31_structural_target",
                "vt31_r1_r22",
                "nas100_only_rule",
                "0900_1000_reference_rule",
            ),
        },
        "global_market_universe": {
            "required": True,
            "dynamic_not_hardcoded": True,
            "sources": _MARKET_UNIVERSE_SOURCES,
            "retain_restricted_markets_as_context": True,
            "retain_unavailable_markets_as_context": True,
            "future_market_additions_require_core_rewrite": False,
            "market_knowledge_implies_trade_authority": False,
        },
        "memory_law": {
            "shared_facts_separate_interpretation": True,
            "historical_closed_episodes_allowed": True,
            "current_episode_future_outcome_forbidden": True,
            "runtime_self_training_from_current_pnl_forbidden": True,
        },
        "specialist_sovereignty": {
            "adapter_contextualizes_only": True,
            "shared_core_may_rewrite_setup": False,
            "shared_core_may_rewrite_entry": False,
            "shared_core_may_rewrite_stop": False,
            "shared_core_may_rewrite_target": False,
            "shared_core_may_authorize_order": False,
            "shared_core_may_authorize_risk": False,
            "qore_risk_sovereign": True,
            "execution_single_authority": True,
        },
        "position_law": {
            "stop_can_improve_or_hold": True,
            "stop_can_widen": False,
            "future_information_allowed": False,
        },
        "shared_essential_intelligence": {
            "universal_stability": {
                "required": True,
                "preferred_observed_drawdown_band_r": ("4", "6"),
                "exceptional_observed_drawdown_target_r": "<4",
                "dd_reduction_cannot_be_bought_with_density_destruction": True,
                "profit_factor_must_increase_vs_trader_baseline": True,
                "stability_must_be_cognitive_not_risk_weighting": True,
                "must_use_current_market_deterioration": True,
                "may_use_closed_trader_performance_state": True,
                "current_trade_outcome_as_input_forbidden": True,
                "future_trade_outcome_as_input_forbidden": True,
                "must_generalize_across_methodologies": True,
                "qore_risk_remains_sovereign": True,
            },
            "dynamic_market_transition": {
                "required": True,
                "continuous_evidence_primary": True,
                "state_summary_secondary": True,
                "must_reason_over_causal_sequences_not_only_snapshots": True,
                "must_detect_deterioration_velocity_and_persistence": True,
                "must_detect_recovery_velocity_and_persistence": True,
                "current_market_evidence_primary": True,
                "pnl_or_trade_outcome_as_primary_state_forbidden": True,
                "future_market_path_forbidden": True,
                "trader_specific_ontology_forbidden": True,
            },
            "third_eye_market_support": {
                "required": True,
                "trader_keeps_methodology_identity": True,
                "shared_supplies_superior_transversal_market_intelligence": True,
                "before_entry_support": True,
                "during_trade_support": True,
                "between_trade_environment_support": True,
                "recovery_support": True,
                "shared_must_detect_information_not_explicitly_captured_by_trader": True,
                "shared_must_not_replace_specialist_methodology": True,
            },
            "adverse_environment_and_loss_cluster_prevention": {
                "required": True,
                "market_behavior_must_be_primary_cause": True,
                "runtime_loss_streak_as_primary_cause_forbidden": True,
                "runtime_pnl_as_primary_cause_forbidden": True,
                "must_detect_environment_formation_before_drawdown_cluster_when_"
                "causally_possible": True,
                "must_detect_persistence_not_only_snapshot": True,
                "must_detect_stabilization_and_edge_restoration": True,
                "offline_realized_outcomes_allowed_for_evaluation_only": True,
            },
            "causal_position_path_asymmetry": {
                "required": True,
                "must_distinguish_terminal_failure_from_recoverable_pullback": True,
                "must_use_only_causal_observations": True,
                "must_protect_established_favorable_journey": True,
                "must_detect_adverse_path_persistence": True,
                "runtime_terminal_outcome_label_forbidden": True,
                "future_path_forbidden": True,
                "density_reduction_as_primary_mechanism_forbidden": True,
            },
            "opportunity_quality_and_winner_protection": {
                "required": True,
                "compare_methodology_valid_opportunities_by_market_support": True,
                "normal_pullback_must_not_be_confused_with_terminal_failure": True,
                "protect_large_winners_from_false_defense": True,
                "extension_requires_causal_market_capacity": True,
            },
            "anomaly_fusion_and_context_memory": {
                "required": True,
                "single_anomaly_should_not_dominate_without_context": True,
                "fuse_volatility_liquidity_structure_momentum_correlation_and_behavior": True,
                "maintain_causal_market_context_across_observations": True,
                "uncertainty_must_remain_explicit": True,
            },
            "ultrafast_instinct_hot_path": {
                "required": True,
                "purpose": (
                    "Shared must recognize the current market/trade situation "
                    "immediately from resident causal state and select the correct "
                    "authority-free support methodology before adverse movement "
                    "can become economically expensive."
                ),
                "resident_state_inputs_only": True,
                "constant_time_fusion_required": True,
                "complexity_contract": "O(1)",
                "history_scan_in_hot_path_forbidden": True,
                "historical_analog_lookup_in_hot_path_forbidden": True,
                "network_io_in_hot_path_forbidden": True,
                "filesystem_io_in_hot_path_forbidden": True,
                "runtime_pnl_input_forbidden": True,
                "terminal_outcome_input_forbidden": True,
                "future_market_input_forbidden": True,
                "must_classify_threat_support_recovery_and_winner_protection": True,
                "must_select_support_methodology_immediately": True,
                "support_methodologies": (
                    "IMMEDIATE_DEFENSE",
                    "PROGRESSIVE_DEFENSE",
                    "WINNER_PROTECTION",
                    "HOLD_AND_MONITOR",
                    "RECOVERY_SUPPORT",
                    "EXTENSION_SUPPORT",
                    "INSUFFICIENT_FAIL_CLOSED",
                ),
                "must_not_rewrite_trader_methodology": True,
                "must_not_reduce_density_as_primary_mechanism": True,
                "shared_order_authority": False,
                "shared_risk_authority": False,
                "shared_sizing_authority": False,
                "shared_execution_authority": False,
                "performance_engineering": {
                    "precompute_heavy_cognition_outside_trade_hot_path": True,
                    "keep_market_state_resident": True,
                    "incremental_updates_required": True,
                    "full_rebuild_per_trade_forbidden": True,
                    "target_single_instinct_fusion_p95_ms": "<1",
                    "target_instinct_plus_adapter_budget_ms": "<10",
                },
            },
            "profit_factor": {
                "required": True,
                "meaning": (
                    "Shared must improve opportunity selection and journey quality "
                    "enough to create materially higher Profit Factor."
                ),
                "cannot_be_achieved_by_risk_weighting_only": True,
                "must_increase_vs_same_trader_baseline": True,
                "pf_improvement_has_priority_over_cosmetic_dd_reduction": True,
            },
            "drawdown": {
                "required": True,
                "meaning": (
                    "Shared must identify bad situations, deterioration, anomaly "
                    "and failed continuation/reversal early enough to reduce DD."
                ),
                "stop_may_improve_or_hold_only": True,
                "stop_widening_forbidden": True,
                "acceptable_target_band_r": ("4", "6"),
                "exceptional_target_r": "<4",
                "density_preservation_required": True,
            },
            "adaptive_journey": {
                "required": True,
                "extend_target_when_market_capacity_supports_it": True,
                "hold_original_target_when_extension_is_unproven": True,
                "defend_or_reduce_loss_when_market_deteriorates": True,
                "decision_must_be_causal_as_of_each_observation": True,
                "future_path_or_terminal_outcome_forbidden": True,
                "shared_has_no_execution_authority": True,
            },
            "market_situation_dimensions": (
                "anomaly",
                "volatility",
                "trend",
                "range",
                "regime",
                "regime_transition",
                "transition_velocity",
                "deterioration_persistence",
                "recovery_persistence",
                "liquidity",
                "structure",
                "displacement",
                "compression",
                "expansion",
                "exhaustion",
                "cross_market_confirmation",
                "cross_market_divergence",
                "historical_analogs",
                "failure_patterns",
                "uncertainty",
                "instinct_situation",
                "support_methodology",
                "threat_urgency",
            ),
            "owner_economic_north_star": {
                "profit_factor_must_increase": True,
                "drawdown_acceptable_band_r": ("4", "6"),
                "drawdown_below_4r_is_preferred_when_pf_and_density_are_preserved": True,
                "density_must_be_preserved": True,
                "mass_abstention_is_not_intelligence": True,
                "total_r_should_be_preserved_or_improved": True,
                "winner_count_and_winner_r_must_be_protected": True,
                "same_opportunity_universe_required_for_claims": True,
                "risk_or_sizing_compression_cannot_claim_shared_success": True,
            },
            "success_requires_all_three": True,
        },
        "shared_research_sequence": {
            "phase_a_shared_intelligence": {
                "status": "ACTIVE_PRIMARY_RESEARCH",
                "scope": "DECISION_PLUS_POSITION_JOURNEY_INTELLIGENCE",
                "capital_potentiation_forbidden_in_phase": True,
                "risk_weighting_forbidden_in_phase": True,
                "journey_intelligence_required_in_phase": True,
                "target_extension_intelligence_required_in_phase": True,
                "loss_defense_intelligence_required_in_phase": True,
                "must_be_formally_accepted_before_phase_b": True,
                "formal_acceptance_requires_temporal_falsification_pass": True,
                "formal_acceptance_requires_material_pf_uplift": True,
                "formal_acceptance_requires_material_dd_reduction": True,
                "formal_acceptance_requires_loss_rejection_quality": True,
                "formal_acceptance_requires_winner_preservation": True,
                "formal_acceptance_requires_density_preservation": True,
                "formal_acceptance_requires_target_extension_quality": True,
                "formal_acceptance_requires_loss_defense_quality": True,
            },
            "phase_b_capital_potentiation": {
                "status": "DEFERRED_BLOCKED",
                "blocked_until_phase_a_formally_accepted": True,
                "shared_intelligence_model_must_be_frozen_first": True,
                "may_not_influence_phase_a_selection": True,
                "capital_or_risk_weighting_belongs_here": True,
            },
        },
        "shared_dual_mission": {
            "mission_1_decision_support": {
                "purpose": (
                    "improve the original trader methodology decision quality "
                    "without rewriting the methodology"
                ),
                "decision_must_precede_entry": True,
                "methodology_rules_unchanged": True,
                "profit_factor_must_increase": True,
                "observed_drawdown_must_decrease": True,
                "protect_winner_retention": True,
                "measure_losses_avoided": True,
                "measure_winners_sacrificed": True,
                "measure_density_retained": True,
            },
            "mission_2_trade_potentiation": {
                "purpose": (
                    "increase the economic quality of trades the trader actually "
                    "takes, reproducing the beneficial economic role of legacy "
                    "Core Stack without owning execution or risk authority"
                ),
                "trader_trade_identity_preserved": True,
                "shared_order_authority": False,
                "shared_risk_authority": False,
                "qore_risk_remains_sovereign": True,
                "profit_factor_must_increase": True,
                "observed_drawdown_may_increase": False,
                "measure_position_journey_uplift": True,
                "measure_capital_efficiency_uplift": True,
                "measure_pf_before_and_after_weighting": True,
            },
            "success_requires_both_missions": True,
        },
        "vt31_benchmark": {
            "owner_raw_methodology": {
                "role": "PRIMARY_FALSIFICATION_BASELINE",
                "core_stack_assistance": False,
                "shared_core_assistance": False,
                "owner_stated_profit_factor": "<1",
                "exact_identity_must_be_recovered_before_numeric_claim": True,
                "shared_must_create_material_positive_edge": True,
            },
            "source_only_r22_formalization": {
                "role": "SECONDARY_UNASSISTED_FORMALIZATION_CONTROL",
                "identity": "ttrades-am-silver-bullet-nq-r2.2",
                "core_stack_assistance": False,
                "shared_core_assistance": False,
                "trade_count_5y": 822,
                "profit_factor_5y": "1.227987023050540462303028923",
                "total_r_5y": "144.2131914306193694297809449",
                "observed_dd_r_5y": "54.78233819598703031487108534",
                "max_losing_streak_5y": 27,
                "evidence_run_id": 35979485763,
                "artifact_id": 10799064861,
                "not_equivalent_to_owner_raw_methodology": True,
            },
            "legacy_core_stack_certified": {
                "role": "SECONDARY_ASSISTED_CEILING",
                "candidate": "VT31_NAS100_STRUCTURAL_TARGET_V1",
                "core_stack_assistance": True,
                "profit_factor_5y": "3.736184576983536",
                "total_r_5y": "68.4017921123",
                "observed_dd_r_5y": "3.7089849073",
                "trade_count_5y": 806,
                "winner_count_5y": 241,
                "certification_loser_count_5y": 565,
                "owner_observed_loser_count": 546,
                "loser_count_requires_reconciliation": True,
                "win_rate_5y_from_certification": "0.2990074441687344913151364764",
                "weighted_pf_uses_capital_weighted_net_r": True,
                "weighted_pf_is_not_signal_quality_pf": True,
                "signal_quality_must_be_measured_unweighted": True,
                "loss_count_imbalance_is_diagnostic_not_pf_proof": True,
            },
            "parity_is_only_safety_gate": True,
            "economic_objective_is_material_uplift": True,
            "shared_success_order": (
                "beat-owner-raw-methodology",
                "beat-source-only-r22-control",
                "challenge-legacy-core-stack-certified",
            ),
            "evaluate_pf": True,
            "evaluate_total_r": True,
            "evaluate_mean_r": True,
            "evaluate_observed_dd": True,
            "evaluate_losing_streak": True,
            "evaluate_mc_dd": True,
            "evaluate_temporal_stability": True,
            "evaluate_wait_abstain_quality": True,
            "evaluate_losses_avoided_vs_winners_sacrificed": True,
            "no_future_features": True,
            "no_calendar_or_fold_identity_edge": True,
        },
        "multi_trader_validation": {
            "required_after_vt31": True,
            "vt31_pass_is_not_global_completion": True,
            "must_include_different_methodologies": True,
            "minimum_metrics_per_trader": (
                "pf_baseline",
                "pf_plus_shared",
                "dd_baseline",
                "dd_plus_shared",
                "total_r_baseline",
                "total_r_plus_shared",
                "losses_avoided",
                "winner_retention",
                "winner_r_retention",
                "density_retained",
                "extend_quality",
                "defend_quality",
            ),
            "shared_is_transversal_only_after_repeatable_cross_methodology_uplift": True,
        },
        "operational_falsification": {
            "required": True,
            "same_realized_market_path_required": True,
            "same_opportunity_universe_required": True,
            "shared_decision_must_precede_outcome": True,
            "shared_shadow_decision_must_be_immutable": True,
            "actual_costs_and_slippage_preferred": True,
            "compare_against_real_vt31_operations": True,
            "poor_real_vt31_period_is_primary_challenge_set": True,
            "shared_must_materially_outperform_on_poor_period": True,
            "shared_failure_to_improve_materially_is_falsification": True,
            "hindsight_reclassification_forbidden": True,
            "post_trade_label_as_runtime_input_forbidden": True,
            "minimum_required_outputs": (
                "profit_factor",
                "total_r",
                "mean_r",
                "observed_drawdown_r",
                "max_losing_streak",
                "monte_carlo_drawdown",
                "density_retained",
                "losses_avoided",
                "winners_sacrificed",
            ),
        },
        "governance": {
            "research_authorized": True,
            "shadow_first": True,
            "vt08_forex_integration": False,
            "vt08_forex_excluded": True,
            "capitalizer_deferred_until_frozen": True,
            "live_deployment_authorized": False,
            "production_authorized": False,
            "real_capital_authorized": False,
            "merge_authorized": False,
        },
    }


def superintelligence_freeze_fingerprint() -> str:
    raw = json.dumps(
        superintelligence_freeze_contract(),
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(raw.encode()).hexdigest()
