"""Owner-frozen maximum Cognitive OS contract for QORE Shared.

Shared is the cognitive, scientific and epistemic operating system of QORE
Core. It may observe, infer, explain, compare, simulate, remember, hypothesize,
falsify, research and communicate. It may not seize sovereign actuation from
traders, CIBO, QORE Risk or Execution.

This contract is intentionally transversal to WP-01..WP-12. It does not create
a parallel work-package sequence.
"""

from __future__ import annotations

from typing import Final

COGNITIVE_OS_CONTRACT_VERSION: Final = (
    "QORE_COGNITIVE_SCIENTIFIC_EPISTEMIC_OS_005"
)

_ALLOWED_SHARED_VERBS: Final = (
    "observe",
    "infer",
    "explain",
    "compare",
    "simulate",
    "remember",
    "hypothesize",
    "falsify",
    "research",
    "communicate",
)

_FORBIDDEN_SHARED_AUTHORITIES: Final = (
    "order_send",
    "position_close",
    "modify_stop",
    "modify_tp",
    "position_size",
    "capital_allocate",
    "risk_authorize",
    "trade_block",
    "trade_force",
)

_REALITY_PLANES: Final = (
    "MARKET_REALITY",
    "CORE_REALITY",
    "COGNITIVE_REALITY",
)

_RUNTIME_TIERS: Final = (
    "TIER_0_SENSORY_SAFETY",
    "TIER_1_WORLD_STATE_REFRESH",
    "TIER_2_BELIEF_HYPOTHESIS_UPDATE",
    "TIER_3_DEEP_COGNITION",
    "TIER_4_SCIENTIFIC_RESEARCH_OFFLINE",
    "TIER_5_TRAINING_DISCOVERY_REPLICATION_OFFLINE",
)

_EPISTEMIC_STATES: Final = (
    "OBSERVED",
    "INFERRED",
    "HYPOTHESIZED",
    "SUPPORTED",
    "FALSIFICATION_SURVIVED",
    "REPLICATED",
    "CERTIFIED",
)

_ABSTENTION_STATES: Final = (
    "INSUFFICIENT_EVIDENCE",
    "UNIDENTIFIABLE",
    "CONTRADICTORY",
    "OOD",
    "DATA_UNRELIABLE",
    "NO_SUPPORTED_HYPOTHESIS",
)

_KNOWLEDGE_LADDER: Final = (
    "OBSERVATION",
    "HYPOTHESIS",
    "EXPERIMENTAL",
    "FALSIFICATION_SURVIVED",
    "REPLICATED",
    "HOLDOUT_VALIDATED",
    "STRESS_VALIDATED",
    "SHADOW_VALIDATED",
    "CERTIFIED",
)

_KNOWLEDGE_STORES: Final = (
    "CERTIFIED_KNOWLEDGE",
    "ADAPTIVE_KNOWLEDGE",
    "EXPERIMENTAL_KNOWLEDGE",
)

_STABILITY_STATES: Final = (
    "STABLE",
    "WATCH",
    "DEFENSIVE_CONTEXT",
    "DISLOCATION",
    "UNKNOWN",
    "RECOVERY",
    "SYSTEM_DEGRADED",
)

_MAXIMUM_COGNITIVE_API: Final = (
    "world",
    "market",
    "cross_market",
    "regime",
    "hypotheses",
    "beliefs",
    "uncertainty",
    "unknowns",
    "anomalies",
    "novelty",
    "transitions",
    "counterfactuals",
    "similar_episodes",
    "causal_context",
    "agency_state",
    "stability",
    "core_health",
    "broker_state",
    "feed_state",
    "get_blindspots",
    "explain",
    "research_state",
    "knowledge_status",
)

_FORBIDDEN_COGNITIVE_API: Final = (
    "enter",
    "exit",
    "resize",
    "block",
    "send_order",
    "allocate_capital",
    "authorize_risk",
)

_MAXIMUM_COGNITIVE_OBJECTIVES: Final = (
    "WorldUnderstanding",
    "InformationQuality",
    "Calibration",
    "KnowledgeReliability",
    "BlindspotReduction",
    "UnknownUnknownDiscovery",
    "ScientificDiscovery",
    "SystemAwareness",
)


def shared_cognitive_os_contract() -> dict[str, object]:
    """Return the Owner-frozen transversal Cognitive OS ceiling."""

    return {
        "schema": "qore.shared.cognitive_os_contract.v2",
        "version": COGNITIVE_OS_CONTRACT_VERSION,
        "owner_directive": (
            "docs/shared/QORE_SHARED_COGNITIVE_OS_OWNER_DIRECTIVE_005.md"
        ),
        "supersedes": "QORE_COGNITIVE_SCIENTIFIC_EPISTEMIC_OS_004",
        "identity": "QORE_SHARED_COGNITIVE_SCIENTIFIC_EPISTEMIC_OPERATING_SYSTEM",
        "mission": (
            "Maintain the best currently justifiable representation of market, "
            "QORE Core, internal beliefs, uncertainty, unknowns and scientific "
            "knowledge while preserving sovereign actuation boundaries."
        ),
        "cognitive_firewall": {
            "read_only_by_default": True,
            "allowed_shared_verbs": _ALLOWED_SHARED_VERBS,
            "forbidden_shared_authorities": _FORBIDDEN_SHARED_AUTHORITIES,
            "shared_may_observe_everything": True,
            "shared_may_understand_everything": True,
            "shared_may_communicate_everything": True,
            "shared_may_seize_sovereign_authority": False,
            "trader_decides_setup": True,
            "cibo_decides_allocation_and_sizing": True,
            "qore_risk_authorizes_capital_risk": True,
            "execution_mutates_broker_state": True,
        },
        "reality_planes": {
            "required": _REALITY_PLANES,
            "market_reality": (
                "price",
                "ticks",
                "ohlc",
                "volume",
                "spread",
                "depth_or_order_flow_if_available",
                "volatility",
                "liquidity_proxies",
                "sessions",
                "cross_market_relationships",
                "rates",
                "indices",
                "fx",
                "commodities",
                "crypto",
                "macro_events",
                "calendar",
                "microstructure",
                "regime",
                "structure",
                "trajectory",
            ),
            "core_reality": (
                "feeds",
                "feed_freshness",
                "latency",
                "broker_connectivity",
                "runtime_health",
                "process_health",
                "clock_drift",
                "data_gaps",
                "symbol_mapping",
                "broker_conditions",
                "execution_quality",
                "spread_anomalies",
                "slippage",
                "rejections",
                "risk_state",
                "capital_state",
                "telemetry_integrity",
                "model_versions",
            ),
            "cognitive_reality": (
                "shared_hypotheses",
                "shared_uncertainties",
                "trader_situation_observations",
                "cibo_capital_conditions",
                "risk_constraints",
                "research_knowledge",
                "experimental_knowledge",
                "certified_knowledge",
                "model_disagreements",
                "unknowns",
            ),
            "market_vs_system_anomaly_must_be_disambiguated": True,
        },
        "digital_twins": {
            "market_digital_twin_required": True,
            "core_digital_twin_required": True,
            "market_world_state_fields": (
                "observable_state",
                "latent_state_distribution",
                "regime_distribution",
                "liquidity_state",
                "structure_state",
                "volatility_state",
                "cross_market_state",
                "agency_state",
                "trajectory_state",
                "anomaly_state",
                "environment_state",
                "uncertainty_state",
                "possible_transitions",
            ),
            "every_inferred_field_requires": (
                "value",
                "confidence",
                "evidence",
                "contradictory_evidence",
                "age",
                "source",
                "quality",
            ),
            "inferred_state_must_not_masquerade_as_observation": True,
            "core_twin_fields": (
                "runtimes",
                "traders",
                "feeds",
                "brokers",
                "risk",
                "capital",
                "execution",
                "latencies",
                "dependencies",
                "failures",
                "telemetry",
                "models",
                "versions",
            ),
        },
        "hierarchical_temporal_cognition": {
            "levels": (
                "tick",
                "sub_second",
                "seconds",
                "M1",
                "M3",
                "M5",
                "M15",
                "H1",
                "H4",
                "D1",
                "session",
                "day",
                "week",
                "macro_regime",
            ),
            "each_level_requires": (
                "state",
                "transition_model",
                "uncertainty",
                "causal_relations",
                "prediction_error",
                "memory",
            ),
            "cross_scale_interaction_model_required": True,
            "lower_timeframe_opposition_is_not_higher_timeframe_reversal": True,
            "multiscale_causality_modes": (
                "bottom_up",
                "top_down",
                "cross_scale",
                "delayed",
                "cross_market",
            ),
        },
        "worlds_and_unknowns": {
            "world_families": (
                "MOMENTUM",
                "LIQUIDITY_AUCTION",
                "MEAN_REVERSION",
                "EVENT_DISLOCATION",
                "INVENTORY",
                "REFLEXIVE_CROWDING",
                "UNKNOWN_UNEXPLAINED",
            ),
            "world_score_inputs": (
                "current_explanatory_power",
                "prediction_error",
                "historical_calibration",
                "causal_consistency",
                "regime_compatibility",
                "ood_score",
            ),
            "unknown_world_first_class": True,
            "known_world_forced_assignment_forbidden": True,
        },
        "latent_and_agency_reasoning": {
            "latent_states_are_probabilistic": True,
            "actor_identity_claims_forbidden_without_observation": True,
            "candidate_latents": (
                "absorption_probability",
                "forced_flow_probability",
                "crowding",
                "liquidity_vulnerability",
                "directional_persistence",
                "market_stress",
                "inventory_imbalance",
                "leadership_strength",
                "participation_intensity",
            ),
            "candidate_agency_mechanisms": (
                "passive_liquidity_provision",
                "aggressive_demand",
                "aggressive_supply",
                "forced_liquidation",
                "short_covering",
                "inventory_rebalancing",
                "systematic_flow",
                "event_repricing",
                "market_making_absorption",
            ),
            "reflexivity_engine_required": True,
            "reflexivity_states": (
                "crowding",
                "self_reinforcement",
                "consensus_instability",
                "breakout_participation",
                "positioning_asymmetry",
                "feedback_loop",
                "reflexive_exhaustion",
            ),
        },
        "causal_and_predictive_reasoning": {
            "causal_grades": (
                "ASSOCIATION",
                "TEMPORAL_DEPENDENCY",
                "CAUSAL_CANDIDATE",
                "FALSIFICATION_SURVIVED",
                "REPLICATED",
                "TRANSPORTABLE",
                "CERTIFIED",
            ),
            "causal_edge_requires": (
                "provenance",
                "markets",
                "regimes",
                "dates",
                "sample_coverage",
                "experiments",
                "failed_experiments",
                "known_confounders",
                "transportability_limits",
            ),
            "predictive_coding_required": True,
            "negative_evidence_engine_required": True,
            "negative_evidence_fields": (
                "expected_event",
                "expected_window",
                "observed_or_absent",
                "surprise",
                "implication",
            ),
            "active_perception_required": True,
            "value_of_information_required": True,
            "value_of_information_objective": (
                "expected_reduction_in_decision_relevant_uncertainty"
            ),
        },
        "belief_and_uncertainty": {
            "multiple_simultaneous_beliefs_required": True,
            "belief_update_requires_evidence": True,
            "uncertainty_components": (
                "aleatoric",
                "epistemic",
                "model_disagreement",
                "data_uncertainty",
                "regime_uncertainty",
                "causal_uncertainty",
                "simulation_uncertainty",
            ),
            "market_unpredictability_must_not_equal_model_ignorance": True,
            "epistemic_states": _EPISTEMIC_STATES,
            "known_likely_possible_unknown_contradictory_required": True,
        },
        "memory_and_knowledge": {
            "episodic_market_memory_required": True,
            "semantic_memory_required": True,
            "cognitive_failure_memory_required": True,
            "cognitive_failure_fields": (
                "belief",
                "why_believed",
                "what_was_missed",
                "failure_class",
                "corrective_lesson",
            ),
            "knowledge_half_life_required": True,
            "knowledge_half_life_fields": (
                "creation_date",
                "last_validation",
                "regime_scope",
                "markets",
                "stability",
                "decay_score",
                "refresh_requirement",
            ),
            "knowledge_transportability_required": True,
            "market_invariant_discovery_required": True,
            "transportability_is_mechanism_conditioned": True,
            "knowledge_stores": _KNOWLEDGE_STORES,
            "promotion_ladder": _KNOWLEDGE_LADDER,
        },
        "representation_and_ontology": {
            "latent_representation_discovery_required": True,
            "human_ontology_is_not_ceiling": True,
            "ontology_evolution_required": True,
            "ontology_operations": (
                "split_concept",
                "merge_concepts",
                "create_concept",
                "retire_concept",
            ),
            "ontology_change_requires_validation": True,
            "market_invariants_preferred_over_local_rule_accumulation": True,
        },
        "graph_transition_journey": {
            "dynamic_graph_market_model_required": True,
            "graph_relations": (
                "leader",
                "follower",
                "decoupling",
                "contagion",
                "correlation_breakdown",
                "causal_propagation",
            ),
            "critical_transition_engine_required": True,
            "transition_warning_candidates": (
                "slower_recovery_from_shocks",
                "rising_model_disagreement",
                "increased_dispersion",
                "correlation_instability",
                "volatility_structural_change",
                "cross_market_breakdown",
            ),
            "journey_intelligence_required": True,
            "irreversibility_recovery_engine_required": True,
            "journey_states": (
                "normal_adversity",
                "recoverable_deterioration",
                "metastable_deterioration",
                "critical_transition",
                "structural_failure",
            ),
        },
        "counterfactual_and_simulation": {
            "conditional_scenario_families_required": True,
            "scenario_fields": (
                "probability",
                "conditions",
                "expected_path_characteristics",
                "tail_behavior",
                "strengthening_evidence",
                "destroying_evidence",
            ),
            "simulation_fidelity_required": True,
            "simulation_fidelity_tests": (
                "path_distribution",
                "volatility_clustering",
                "tails",
                "transition_frequency",
                "regime_persistence",
                "cross_market_dependencies",
                "spread_dynamics",
            ),
        },
        "scientific_society": {
            "specialists": (
                "LIQUIDITY",
                "STRUCTURE",
                "VOLATILITY",
                "CROSS_MARKET",
                "REGIME",
                "TRAJECTORY",
                "CAUSALITY",
                "ANOMALY",
                "AGENCY",
                "MACRO_TIME",
                "INFRASTRUCTURE",
                "BROKER",
                "EPISTEMICS",
            ),
            "simple_majority_vote_forbidden": True,
            "specialist_weighting_requires": (
                "historical_calibration",
                "current_regime_competence",
                "ood",
                "evidence_quality",
                "recent_prediction_error",
                "specialization_relevance",
            ),
            "cognitive_arbitration_required": True,
            "adversarial_roles": ("DEFENDER", "PROSECUTOR", "SKEPTIC"),
        },
        "metacognition": {
            "self_model_required": True,
            "self_model_fields": (
                "models_currently_relied_on",
                "model_strengths",
                "model_weaknesses",
                "stale_knowledge",
                "unstable_representations",
                "calibration_failures",
            ),
            "meta_reasoning_policy_required": True,
            "value_of_computation_required": True,
            "value_of_computation_objective": (
                "expected_information_gain_minus_computation_cost"
            ),
            "runtime_tiers": _RUNTIME_TIERS,
            "distributed_cognitive_attention_required": True,
            "surprise_engine_required": True,
            "novelty_engine_required": True,
        },
        "core_infrastructure_and_broker_intelligence": {
            "core_stability_separate_from_market_stability": True,
            "infrastructure_specialist_required": True,
            "broker_specialist_required": True,
            "infrastructure_detection_scope": (
                "feed_degradation",
                "clock_drift",
                "latency_anomalies",
                "broker_mismatch",
                "symbol_mapping_errors",
                "data_holes",
                "execution_degradation",
                "spread_anomalies",
                "runtime_instability",
            ),
            "broker_model_scope": (
                "spread_behavior",
                "slippage_distribution",
                "session_behavior",
                "execution_latency",
                "rejection_patterns",
                "symbol_specifics",
                "liquidity_windows",
                "pre_close_deterioration",
            ),
            "infrastructure_intelligence_may_auto_mutate_runtime": False,
        },
        "interfaces_and_blindspots": {
            "trader_cognitive_adapters_required": True,
            "adapter_translates_generic_context_only": True,
            "adapter_may_mutate_methodology": False,
            "blindspot_engine_required": True,
            "blindspot_fields": (
                "what_component_sees",
                "what_component_does_not_observe",
                "external_context_seen_by_shared",
                "potentially_relevant_missing_information",
            ),
            "inter_trader_rule_copy_forbidden": True,
            "inter_trader_generic_phenomenon_abstraction_required": True,
            "cibo_context_interface_allowed": True,
            "cibo_control_forbidden": True,
            "risk_context_interface_allowed": True,
            "risk_control_forbidden": True,
        },
        "scientific_system": {
            "research_priority_engine_required": True,
            "priority_inputs": (
                "high_prediction_error",
                "recurrent_unexplained_states",
                "large_uncertainty",
                "frequent_cognitive_failures",
                "high_downstream_importance",
                "knowledge_decay",
                "cross_market_anomalies",
            ),
            "autonomous_experiment_design_required": True,
            "anti_leakage_engine_required": True,
            "reproducibility_engine_required": True,
            "reproducibility_fields": (
                "dataset_version",
                "code_version",
                "model_version",
                "seed",
                "configuration",
                "provenance",
                "result_hash",
            ),
            "governed_self_improvement_required": True,
            "meta_scientific_engine_required": True,
        },
        "trust_and_failure_modes": {
            "provenance_graph_required": True,
            "anti_hallucination_architecture_required": True,
            "abstention_states": _ABSTENTION_STATES,
            "security_requirements": (
                "read_only_by_default",
                "signed_model_artifacts",
                "immutable_provenance",
                "versioned_knowledge",
                "role_separated_permissions",
                "sandbox_research",
                "no_broker_mutation_authority",
                "audit_logs",
                "tamper_detection",
            ),
            "degraded_mode_required": True,
            "partial_input_failure_must_lower_confidence_not_crash_core": True,
            "shared_offline_must_not_break_trader_sovereignty": True,
            "shared_must_not_be_hidden_methodology_dependency": True,
        },
        "measurement": {
            "primary_intelligence_scorecard": (
                "state_reconstruction_accuracy",
                "prediction_calibration",
                "transition_forecast_calibration",
                "causal_falsification_quality",
                "ood_detection",
                "novelty_detection",
                "uncertainty_calibration",
                "cross_market_consistency",
                "knowledge_stability",
                "transportability",
                "representation_quality",
                "counterfactual_fidelity",
                "analogue_retrieval_quality",
                "cognitive_failure_reduction",
                "research_reproducibility",
                "knowledge_promotion_precision",
                "blindspot_discovery",
                "infrastructure_anomaly_detection",
                "broker_state_accuracy",
                "explanation_fidelity",
                "latency",
                "availability",
            ),
            "downstream_effects": (
                "trader_decision_quality",
                "profit_factor",
                "drawdown",
                "total_r",
                "tail_risk",
                "capital_efficiency",
                "execution_quality",
                "operational_reliability",
            ),
            "downstream_effects_are_not_shared_identity": True,
        },
        "unknown_unknown_discovery": {
            "second_order_blindspot_detection_required": True,
            "must_search_for_uninstrumented_observation_spaces": True,
            "must_search_for_unmodeled_dependencies": True,
            "must_distinguish_unknown_unknown_from_data_corruption": True,
            "must_not_force_unknown_unknown_into_known_ontology": True,
            "unknown_unknown_discovery_remains_research_until_validated": True,
        },
        "systemic_stability": {
            "market_stability_required": True,
            "core_stability_required": True,
            "broker_stability_required": True,
            "cognitive_stability_required": True,
            "systemic_stress_required": True,
            "descriptive_states": _STABILITY_STATES,
            "stability_state_is_not_trading_command": True,
        },
        "maximum_cognitive_api": {
            "read_only_surface": _MAXIMUM_COGNITIVE_API,
            "forbidden_actuation_surface": _FORBIDDEN_COGNITIVE_API,
            "api_may_mutate_broker": False,
            "api_may_allocate_capital": False,
            "api_may_authorize_risk": False,
            "api_may_mutate_trader_methodology": False,
        },
        "objective_law": {
            "primary_objectives": _MAXIMUM_COGNITIVE_OBJECTIVES,
            "profit_factor_is_primary_objective": False,
            "drawdown_is_primary_objective": False,
            "price_prediction_is_primary_objective": False,
            "downstream_economic_effects_remain_certification_evidence": True,
            "no_trading_authority": True,
            "no_risk_authority": True,
            "no_capital_authority": True,
            "no_execution_authority": True,
        },
        "explanation_contract": {
            "every_material_output_must_answer": (
                "what_do_you_believe",
                "why",
                "what_contradicts_it",
                "how_certain_are_you",
                "what_would_falsify_it",
                "what_do_you_not_know",
                "what_evidence_is_most_useful_next",
            ),
        },
    }
