"""Owner-directed cognitive architecture contract for Shared Brain.

Shared is the central market-intelligence operating system of Core. It observes,
models, reasons, remembers, falsifies, simulates, learns and communicates.
It does not replace specialist methodology, QORE Risk or Execution sovereignty.
"""

from __future__ import annotations

from typing import Final

SHARED_BRAIN_ARCHITECTURE_VERSION: Final = "QORE_META_COGNITIVE_SCIENTIFIC_INTELLIGENCE_003"

_COGNITIVE_PIPELINE: Final = (
    "MARKET_OBSERVATION",
    "HIERARCHICAL_WORLD_MODEL",
    "MULTI_WORLD_COMPETITION",
    "LATENT_STATE_RECONSTRUCTION",
    "PREDICTIVE_CODING",
    "DYNAMIC_CAUSAL_GRAPH",
    "COMPETING_CAUSAL_HYPOTHESES",
    "ACTIVE_PERCEPTION",
    "BELIEF_STATE",
    "GRAPH_MARKET_MODEL",
    "TEMPORAL_CAUSAL_MODEL",
    "SCENARIO_TREE",
    "COUNTERFACTUAL_WORLD_SIMULATION",
    "UNCERTAINTY_DECOMPOSITION",
    "METACOGNITION",
    "EPISODIC_AND_SEMANTIC_MEMORY",
    "TRAJECTORY_INTELLIGENCE",
    "STABILITY_INTELLIGENCE",
    "DECISION_INTELLIGENCE",
    "AUTONOMOUS_RESEARCH",
    "GOVERNED_KNOWLEDGE_PROMOTION",
    "SHARED_SITUATION",
)

_REQUIRED_CAPABILITIES: Final = (
    "PROBABILISTIC_MARKET_DIGITAL_TWIN",
    "FEDERATION_OF_WORLDS",
    "CAUSAL_DISCOVERY_ENGINE",
    "MARKET_REPRESENTATION_DISCOVERY",
    "MARKET_AGENCY_MODEL",
    "SCIENTIFIC_SOCIETY",
    "COGNITIVE_ARBITRATION",
    "META_COGNITIVE_SCIENTIFIC_INTELLIGENCE",
    "HIERARCHICAL_MULTI_TIMESCALE_WORLD_MODEL",
    "MULTI_WORLD_ENGINE",
    "LATENT_STATE_RECONSTRUCTION",
    "PREDICTIVE_CODING",
    "NEURAL_SYMBOLIC_REASONING",
    "MARKET_FOUNDATION_MODEL_INTERFACE",
    "DYNAMIC_GRAPH_MARKET_MODEL",
    "TEMPORAL_CAUSAL_TRANSFORMER_INTERFACE",
    "ALEATORIC_EPISTEMIC_UNCERTAINTY_DECOMPOSITION",
    "ENSEMBLE_OF_MINDS",
    "COUNTERFACTUAL_WORLD_SIMULATION",
    "META_LEARNING",
    "CONTINUAL_LEARNING_WITHOUT_CATASTROPHIC_FORGETTING",
    "WORLD_MODEL",
    "DYNAMIC_CAUSAL_GRAPH",
    "EPISODIC_MARKET_MEMORY",
    "SEMANTIC_MARKET_MEMORY",
    "PREDICTIVE_STATE_MODEL",
    "ACTIVE_PERCEPTION",
    "PROBABILISTIC_BELIEF_STATE",
    "MARKET_PHYSICS_CONSTRAINTS",
    "METACOGNITION",
    "SPECIALIST_REASONING_COUNCIL",
    "ADVERSARIAL_HYPOTHESIS_TESTING",
    "LATENT_CONCEPT_REASONING",
    "TRAJECTORY_INTELLIGENCE",
    "STABILITY_ENGINE",
    "MACHINE_SCIENTIFIC_DISCOVERY",
    "AUTONOMOUS_RESEARCH_ENGINE",
    "GOVERNED_KNOWLEDGE_PROMOTION",
)

_KNOWLEDGE_TIERS: Final = (
    "RESEARCH_KNOWLEDGE",
    "VALIDATED_KNOWLEDGE",
    "CERTIFIED_KNOWLEDGE",
)


def shared_brain_architecture_contract() -> dict[str, object]:
    """Return the frozen ceiling architecture for Shared cognition."""

    return {
        "schema": "qore.shared_brain.architecture_contract.v2",
        "version": SHARED_BRAIN_ARCHITECTURE_VERSION,
        "role": "QORE_META_COGNITIVE_SCIENTIFIC_MARKET_OPERATING_SYSTEM",
        "objective": (
            "Continuously reconstruct the most plausible hidden market state, "
            "maintain competing internal world models, predict state transitions, "
            "measure prediction error and uncertainty, falsify its own beliefs, "
            "simulate plausible futures, learn without destroying certified "
            "knowledge, and communicate generic market intelligence to sovereign "
            "specialist traders."
        ),
        "pipeline": _COGNITIVE_PIPELINE,
        "maximum_ceiling_program": "docs/shared/QORE_SHARED_MAXIMUM_COGNITIVE_CEILING_ROADMAP.md",
        "maximum_ceiling_master_issue": 638,
        "maximum_ceiling_work_packages": tuple(range(639, 651)),
        "required_capabilities": _REQUIRED_CAPABILITIES,
        "hierarchical_world_model_law": {
            "multiple_temporal_levels_required": True,
            "minimum_levels": (
                "ticks_or_microstructure",
                "seconds",
                "M1",
                "M5",
                "M15",
                "H1",
                "H4",
                "daily",
                "cross_market_regime",
                "macro_regime",
            ),
            "each_level_has_own_state_and_transition_model": True,
            "cross_level_reconciliation_required": True,
            "lower_timeframe_pressure_cannot_imply_higher_timeframe_reversal": True,
            "cross_level_contradiction_must_remain_explicit": True,
        },
        "multi_world_law": {
            "multiple_internal_world_models_required": True,
            "minimum_world_families": (
                "liquidity_driven",
                "momentum_driven",
                "mean_reversion",
                "event_or_dislocation",
                "unresolved",
            ),
            "world_models_compete_on_prediction_error": True,
            "world_models_compete_on_causal_consistency": True,
            "world_models_compete_on_calibration": True,
            "world_models_compete_on_trajectory_accuracy": True,
            "single_universal_market_logic_assumption_forbidden": True,
        },
        "latent_reconstruction_law": {
            "hidden_state_estimation_required": True,
            "minimum_latent_concepts": (
                "hidden_liquidity_pressure",
                "latent_directional_intent",
                "institutional_participation_probability",
                "absorption_probability",
                "inventory_imbalance",
                "liquidity_vulnerability",
                "market_stress",
                "crowding",
            ),
            "latent_state_must_be_probabilistic": True,
            "latent_state_is_inferred_from_effects_not_claimed_as_observed": True,
        },
        "predictive_coding_law": {
            "expected_vs_observed_loop_required": True,
            "minimum_predictions": (
                "expected_volatility",
                "expected_displacement",
                "expected_retracement_depth",
                "expected_intermarket_reaction",
                "expected_liquidity_response",
            ),
            "prediction_error_is_cognitive_evidence": True,
            "prediction_error_must_update_world_and_hypothesis_beliefs": True,
            "failed_prediction_must_not_be_treated_as_simple_signal_failure": True,
        },
        "neural_symbolic_law": {
            "representation_learning_allowed": True,
            "probabilistic_inference_required": True,
            "symbolic_reasoning_required": True,
            "causal_graph_reasoning_required": True,
            "hard_market_constraints_required": True,
            "interpretable_concept_layer_required": True,
            "deep_model_output_cannot_bypass_symbolic_or_causal_checks": True,
        },
        "market_foundation_model_law": {
            "qore_specific_sequence_model_is_long_term_target": True,
            "not_an_llm": True,
            "self_supervised_pretraining_preferred": True,
            "supported_modalities_may_include": (
                "ticks",
                "ohlcv",
                "spread",
                "order_flow",
                "volatility",
                "cross_market_relations",
                "sessions",
                "events",
                "trajectory_sequences",
            ),
            "masked_reconstruction_allowed": True,
            "future_state_prediction_allowed_for_training_only": True,
            "runtime_future_information_forbidden": True,
            "learned_concepts_may_extend_human_defined_ontology": True,
        },
        "graph_market_model_law": {
            "dynamic_market_relationship_graph_required": True,
            "lead_lag_relationships_must_be_learned_not_hardcoded": True,
            "relationship_break_detection_required": True,
            "dynamic_correlation_stability_required": True,
            "cross_market_context_does_not_imply_trade_authority": True,
        },
        "temporal_causal_law": {
            "context_dependent_causality_required": True,
            "sequence_and_regime_conditioning_required": True,
            "precedence_alone_is_not_causality": True,
            "causal_claims_require_falsification_and_replication": True,
        },
        "uncertainty_law": {
            "aleatoric_uncertainty_required": True,
            "epistemic_uncertainty_required": True,
            "model_disagreement_required": True,
            "regime_familiarity_required": True,
            "novelty_and_ood_required": True,
            "calibration_required": True,
            "high_epistemic_uncertainty_must_reduce_cognitive_assertiveness": True,
            "high_aleatoric_uncertainty_must_not_be_mislabeled_model_failure": True,
        },
        "ensemble_of_minds_law": {
            "heterogeneous_specialists_required": True,
            "candidate_model_families": (
                "transformer",
                "state_space_model",
                "graph_model",
                "bayesian_model",
                "causal_model",
                "symbolic_engine",
                "trajectory_model",
                "anomaly_detector",
            ),
            "agreement_may_raise_confidence": True,
            "disagreement_must_raise_uncertainty": True,
            "single_model_supremacy_forbidden": True,
        },
        "counterfactual_world_law": {
            "multiple_plausible_future_paths_required": True,
            "path_distribution_required": True,
            "tail_risk_estimation_required": True,
            "failure_probability_required": True,
            "counterfactuals_must_respect_information_available_at_each_time": True,
            "hindsight_oracle_counterfactuals_forbidden": True,
        },
        "meta_learning_law": {
            "rapid_novel_regime_adaptation_required": True,
            "nearest_known_structure_retrieval_required": True,
            "adaptation_must_be_validated_before_knowledge_promotion": True,
            "new_market_learning_must_not_require_core_architecture_rewrite": True,
        },
        "continual_learning_law": {
            "stable_knowledge_separated_from_recent_adaptation": True,
            "recent_adaptation_separated_from_experimental_knowledge": True,
            "catastrophic_forgetting_protection_required": True,
            "experimental_knowledge_cannot_replace_certified_knowledge_directly": True,
            "rollback_and_lineage_required": True,
        },
        "autonomous_research_law": {
            "error_pattern_detection_required": True,
            "hypothesis_generation_required": True,
            "experiment_design_required": True,
            "leakage_prevention_required": True,
            "falsification_required": True,
            "holdout_required": True,
            "stress_required": True,
            "replication_required": True,
            "knowledge_tiers": _KNOWLEDGE_TIERS,
            "research_to_validated_requires_evidence": True,
            "validated_to_certified_requires_owner_governed_gate": True,
            "research_may_not_self_promote_to_runtime": True,
        },
        "world_model_law": {
            "price_direction_prediction_is_not_primary_objective": True,
            "continuous_market_world_state_required": True,
            "observed_and_latent_state_separated": True,
            "causal_relations_required": True,
            "scenario_distribution_required": True,
            "expected_state_transitions_required": True,
            "anomaly_and_uncertainty_required": True,
        },
        "reasoning_law": {
            "multiple_competing_hypotheses_required": True,
            "single_story_commitment_forbidden": True,
            "hypothesis_falsification_required": True,
            "active_evidence_requests_required": True,
            "online_belief_update_required": True,
            "unknown_state_must_remain_explicit": True,
            "concept_reasoning_preferred_over_rule_accumulation": True,
            "threshold_patchwork_cannot_be_primary_intelligence": True,
        },
        "trajectory_law": {
            "full_opportunity_journey_required": True,
            "normal_adversity_must_not_equal_structural_deterioration": True,
            "temporary_pullback_must_not_equal_failed_thesis": True,
            "market_noise_must_not_equal_stop_pressure": True,
            "hold_defend_exit_extend_must_be_causally_explainable": True,
        },
        "sovereignty_law": {
            "shared_observes_understands_reasons_learns_and_communicates": True,
            "shared_is_not_a_trader": True,
            "shared_does_not_own_specialist_methodology": True,
            "specialist_traders_remain_sovereign": True,
            "qore_risk_remains_sovereign": True,
            "execution_remains_sovereign": True,
            "shared_direct_order_authority": False,
            "shared_sizing_authority": False,
            "shared_risk_budget_authority": False,
        },
    }
