"""Stable infrastructure boundary contracts for QORE."""

from qore.infrastructure.ingestion import (
    ExternalMarketDataPayloadPort,
    ExternalOhlcPayload,
    ExternalQuotePayload,
    IngestionError,
    IngestionValidationError,
    MarketDataIngestionFlow,
)
from qore.infrastructure.market_data import (
    Instrument,
    MarketDataError,
    MarketDataPort,
    MarketDataSnapshotId,
    MarketDataValidationError,
    OhlcRequest,
    OhlcSnapshot,
    QuoteRequest,
    QuoteSnapshot,
    Timeframe,
)
from qore.infrastructure.persistence import (
    LoadPersistenceRequest,
    PersistenceConflictError,
    PersistenceError,
    PersistenceKey,
    PersistencePort,
    PersistenceValidationError,
    PersistenceVersion,
    SavePersistenceRequest,
    StoredRecord,
)
from qore.infrastructure.ports import (
    AdapterId,
    ExternalHealth,
    ExternalPort,
    ExternalPortError,
    ExternalRequestMetadata,
    ExternalSourceDescriptor,
    PortAvailability,
    PortName,
    PortUnavailableError,
    PortValidationError,
    ReadExternalPort,
    SourceId,
    WriteExternalPort,
)
from qore.infrastructure.reference_adapters import (
    ReferenceAdapterCopyError,
    ReferenceAdapterError,
    ReferenceAdapterValidationError,
    ReferenceDataNotFoundError,
    ReferenceMarketDataAdapter,
    ReferencePersistenceAdapter,
)
from qore.infrastructure.reference_payload_adapters import (
    ReferenceExternalMarketDataPayloadAdapter,
)

__all__ = [
    "AdapterId",
    "ExternalHealth",
    "ExternalMarketDataPayloadPort",
    "ExternalOhlcPayload",
    "ExternalPort",
    "ExternalPortError",
    "ExternalQuotePayload",
    "ExternalRequestMetadata",
    "ExternalSourceDescriptor",
    "IngestionError",
    "IngestionValidationError",
    "Instrument",
    "LoadPersistenceRequest",
    "MarketDataError",
    "MarketDataIngestionFlow",
    "MarketDataPort",
    "MarketDataSnapshotId",
    "MarketDataValidationError",
    "OhlcRequest",
    "OhlcSnapshot",
    "PersistenceConflictError",
    "PersistenceError",
    "PersistenceKey",
    "PersistencePort",
    "PersistenceValidationError",
    "PersistenceVersion",
    "PortAvailability",
    "PortName",
    "PortUnavailableError",
    "PortValidationError",
    "QuoteRequest",
    "QuoteSnapshot",
    "ReadExternalPort",
    "ReferenceAdapterCopyError",
    "ReferenceAdapterError",
    "ReferenceAdapterValidationError",
    "ReferenceDataNotFoundError",
    "ReferenceExternalMarketDataPayloadAdapter",
    "ReferenceMarketDataAdapter",
    "ReferencePersistenceAdapter",
    "SavePersistenceRequest",
    "SourceId",
    "StoredRecord",
    "Timeframe",
    "WriteExternalPort",
]
